#!/bin/sh
set -e

case "$1" in
    configure)
        # add stc binary to PATH
        echo 'export PATH=$PATH:/usr/bin/swift-t/stc/bin' >> /etc/profile
	;;

    upgrade|abort-upgrade)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
