/* AUTOGENERATED HEADER - DO NOT EDIT */

#include <stddef.h>

extern const unsigned char turbine_lib_helpers_tcl[];
extern const size_t turbine_lib_helpers_tcl_len;
extern const unsigned char turbine_lib_turbine_tcl[];
extern const size_t turbine_lib_turbine_tcl_len;
extern const unsigned char turbine_lib_worker_tcl[];
extern const size_t turbine_lib_worker_tcl_len;
extern const unsigned char turbine_lib_data_tcl[];
extern const size_t turbine_lib_data_tcl_len;
extern const unsigned char turbine_lib_functions_tcl[];
extern const size_t turbine_lib_functions_tcl_len;
extern const unsigned char turbine_lib_assert_tcl[];
extern const size_t turbine_lib_assert_tcl_len;
extern const unsigned char turbine_lib_logical_tcl[];
extern const size_t turbine_lib_logical_tcl_len;
extern const unsigned char turbine_lib_arith_tcl[];
extern const size_t turbine_lib_arith_tcl_len;
extern const unsigned char turbine_lib_string_tcl[];
extern const size_t turbine_lib_string_tcl_len;
extern const unsigned char turbine_lib_container_tcl[];
extern const size_t turbine_lib_container_tcl_len;
extern const unsigned char turbine_lib_rand_tcl[];
extern const size_t turbine_lib_rand_tcl_len;
extern const unsigned char turbine_lib_reductions_tcl[];
extern const size_t turbine_lib_reductions_tcl_len;
extern const unsigned char turbine_lib_stats_tcl[];
extern const size_t turbine_lib_stats_tcl_len;
extern const unsigned char turbine_lib_io_tcl[];
extern const size_t turbine_lib_io_tcl_len;
extern const unsigned char turbine_lib_updateable_tcl[];
extern const size_t turbine_lib_updateable_tcl_len;
extern const unsigned char turbine_lib_sys_tcl[];
extern const size_t turbine_lib_sys_tcl_len;
extern const unsigned char turbine_lib_blob_tcl[];
extern const size_t turbine_lib_blob_tcl_len;
extern const unsigned char turbine_lib_mpe_tcl[];
extern const size_t turbine_lib_mpe_tcl_len;
extern const unsigned char turbine_lib_files_tcl[];
extern const size_t turbine_lib_files_tcl_len;
extern const unsigned char turbine_lib_location_tcl[];
extern const size_t turbine_lib_location_tcl_len;
extern const unsigned char turbine_lib_checkpoint_tcl[];
extern const size_t turbine_lib_checkpoint_tcl_len;
extern const unsigned char turbine_lib_app_tcl[];
extern const size_t turbine_lib_app_tcl_len;
extern const unsigned char turbine_lib_langs_tcl[];
extern const size_t turbine_lib_langs_tcl_len;
extern const unsigned char turbine_lib_gemtc_worker_tcl[];
extern const size_t turbine_lib_gemtc_worker_tcl_len;

static const unsigned char *turbine_lib_src[24];
static size_t turbine_lib_src_lens[24];
static const char *turbine_lib_src_names[24];
static const size_t turbine_lib_src_len = 24;

static const char *turbine_lib_src_filenames[] = {
  "lib/helpers.tcl",
  "lib/turbine.tcl",
  "lib/worker.tcl",
  "lib/data.tcl",
  "lib/functions.tcl",
  "lib/assert.tcl",
  "lib/logical.tcl",
  "lib/arith.tcl",
  "lib/string.tcl",
  "lib/container.tcl",
  "lib/rand.tcl",
  "lib/reductions.tcl",
  "lib/stats.tcl",
  "lib/io.tcl",
  "lib/updateable.tcl",
  "lib/sys.tcl",
  "lib/blob.tcl",
  "lib/mpe.tcl",
  "lib/files.tcl",
  "lib/location.tcl",
  "lib/checkpoint.tcl",
  "lib/app.tcl",
  "lib/langs.tcl",
  "lib/gemtc_worker.tcl",
};

static inline void turbine_lib_src_init(void) {
  turbine_lib_src[0] = turbine_lib_helpers_tcl;
  turbine_lib_src_lens[0] = turbine_lib_helpers_tcl_len;
  turbine_lib_src_names[0] = "turbine_lib_helpers_tcl";
  turbine_lib_src[1] = turbine_lib_turbine_tcl;
  turbine_lib_src_lens[1] = turbine_lib_turbine_tcl_len;
  turbine_lib_src_names[1] = "turbine_lib_turbine_tcl";
  turbine_lib_src[2] = turbine_lib_worker_tcl;
  turbine_lib_src_lens[2] = turbine_lib_worker_tcl_len;
  turbine_lib_src_names[2] = "turbine_lib_worker_tcl";
  turbine_lib_src[3] = turbine_lib_data_tcl;
  turbine_lib_src_lens[3] = turbine_lib_data_tcl_len;
  turbine_lib_src_names[3] = "turbine_lib_data_tcl";
  turbine_lib_src[4] = turbine_lib_functions_tcl;
  turbine_lib_src_lens[4] = turbine_lib_functions_tcl_len;
  turbine_lib_src_names[4] = "turbine_lib_functions_tcl";
  turbine_lib_src[5] = turbine_lib_assert_tcl;
  turbine_lib_src_lens[5] = turbine_lib_assert_tcl_len;
  turbine_lib_src_names[5] = "turbine_lib_assert_tcl";
  turbine_lib_src[6] = turbine_lib_logical_tcl;
  turbine_lib_src_lens[6] = turbine_lib_logical_tcl_len;
  turbine_lib_src_names[6] = "turbine_lib_logical_tcl";
  turbine_lib_src[7] = turbine_lib_arith_tcl;
  turbine_lib_src_lens[7] = turbine_lib_arith_tcl_len;
  turbine_lib_src_names[7] = "turbine_lib_arith_tcl";
  turbine_lib_src[8] = turbine_lib_string_tcl;
  turbine_lib_src_lens[8] = turbine_lib_string_tcl_len;
  turbine_lib_src_names[8] = "turbine_lib_string_tcl";
  turbine_lib_src[9] = turbine_lib_container_tcl;
  turbine_lib_src_lens[9] = turbine_lib_container_tcl_len;
  turbine_lib_src_names[9] = "turbine_lib_container_tcl";
  turbine_lib_src[10] = turbine_lib_rand_tcl;
  turbine_lib_src_lens[10] = turbine_lib_rand_tcl_len;
  turbine_lib_src_names[10] = "turbine_lib_rand_tcl";
  turbine_lib_src[11] = turbine_lib_reductions_tcl;
  turbine_lib_src_lens[11] = turbine_lib_reductions_tcl_len;
  turbine_lib_src_names[11] = "turbine_lib_reductions_tcl";
  turbine_lib_src[12] = turbine_lib_stats_tcl;
  turbine_lib_src_lens[12] = turbine_lib_stats_tcl_len;
  turbine_lib_src_names[12] = "turbine_lib_stats_tcl";
  turbine_lib_src[13] = turbine_lib_io_tcl;
  turbine_lib_src_lens[13] = turbine_lib_io_tcl_len;
  turbine_lib_src_names[13] = "turbine_lib_io_tcl";
  turbine_lib_src[14] = turbine_lib_updateable_tcl;
  turbine_lib_src_lens[14] = turbine_lib_updateable_tcl_len;
  turbine_lib_src_names[14] = "turbine_lib_updateable_tcl";
  turbine_lib_src[15] = turbine_lib_sys_tcl;
  turbine_lib_src_lens[15] = turbine_lib_sys_tcl_len;
  turbine_lib_src_names[15] = "turbine_lib_sys_tcl";
  turbine_lib_src[16] = turbine_lib_blob_tcl;
  turbine_lib_src_lens[16] = turbine_lib_blob_tcl_len;
  turbine_lib_src_names[16] = "turbine_lib_blob_tcl";
  turbine_lib_src[17] = turbine_lib_mpe_tcl;
  turbine_lib_src_lens[17] = turbine_lib_mpe_tcl_len;
  turbine_lib_src_names[17] = "turbine_lib_mpe_tcl";
  turbine_lib_src[18] = turbine_lib_files_tcl;
  turbine_lib_src_lens[18] = turbine_lib_files_tcl_len;
  turbine_lib_src_names[18] = "turbine_lib_files_tcl";
  turbine_lib_src[19] = turbine_lib_location_tcl;
  turbine_lib_src_lens[19] = turbine_lib_location_tcl_len;
  turbine_lib_src_names[19] = "turbine_lib_location_tcl";
  turbine_lib_src[20] = turbine_lib_checkpoint_tcl;
  turbine_lib_src_lens[20] = turbine_lib_checkpoint_tcl_len;
  turbine_lib_src_names[20] = "turbine_lib_checkpoint_tcl";
  turbine_lib_src[21] = turbine_lib_app_tcl;
  turbine_lib_src_lens[21] = turbine_lib_app_tcl_len;
  turbine_lib_src_names[21] = "turbine_lib_app_tcl";
  turbine_lib_src[22] = turbine_lib_langs_tcl;
  turbine_lib_src_lens[22] = turbine_lib_langs_tcl_len;
  turbine_lib_src_names[22] = "turbine_lib_langs_tcl";
  turbine_lib_src[23] = turbine_lib_gemtc_worker_tcl;
  turbine_lib_src_lens[23] = turbine_lib_gemtc_worker_tcl_len;
  turbine_lib_src_names[23] = "turbine_lib_gemtc_worker_tcl";
}

